### ISSUE TITLE
Implement repeating group widget mvp

### ISSUE THREAD

**Issue by vincent-karuri** [OpenSRP/opensrp-client-native-form#172]
-  [x] Include edit text as part of the repeating group widget
- [x] Create new root linear layout programatically. Add a unique id to this root repeating group linear layout  
- [x] Add repeating group layout definition as a nested value within the repeating group form element definition, so that we have the main edit text reference field followed by the repeating group layout, within the root linear layout
- [x] Add a static hash map of linear layout unique id to JSONArray representing the repeating group elements, which is parsed once when the repeating group is being set up
- [x] Add an edit text listener initially, and as a test (should add confirm button later), to the reference edit text in `attachLayout` or `getViewsFromJson` factory methods. 
- [x] On pressing `Enter` or `Done`, get the view id of root linear layout using `getParent` and use the id to add/remove views to/from the root layout
- [x] Call `getViewsFromJson` for each widget in the repeating group and add all elements returned from this function to the repeating group root layout. It should have all necessary validation added
- [x] To do this ^, parse each repeating group's element type, get factory for each type using `map.get(type)` in `JsonFormInteractor`, call the factory's `getViewFromJson` and pass the widget's JsonObject
- [x] Call the validate method in each widget's factory when validating elements in the repeating group (Edit: no need for this, validation is added for free when the above method is used to get widget layouts)
- [x]  Limit the number of repeating fields e.g. to 35 to avoid performance hits
- [x] Add a suffix of a unique string to field keys so it's easy to write back values to the form Json
- [x] Add relevance checks within the repeating group
- [x] Add a progress dialog as repeating group entries are being created
- [x] For deleted repeating group entries, the corresponding json object should be removed from the json form object
- [x] Add ability to specify reference edit text hint
- [x] Add ability to specify repeating group label text which will have a serially increasing suffix integer added to it
- [x] Add support for relative max validator

**Comment by vincent-karuri** [comment]
Assumptions:
- No validation for matching number in reference edit text and actual number of repeated groups
- Repeating group is not collapsible
- User cannot delete repeating group entries that they no longer need
- Number in repeating group reference edit text will not need to be less than what is initially input and confirmed using the tick button, and can only be more

**Comment by vincent-karuri** [comment]
@githengi FYI

**Comment by githengi** [comment]
instead of text-watcher use on focus lost event

**Comment by vincent-karuri** [comment]
Using `Done` button clicked event instead?
