### ISSUE TITLE
Fix NumericDatePicker bug

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/opensrp-client-native-form#567]
A Bug in the NumericDatePicker class which sometimes causes crash when one selects a date out of the range of allowed dates (min and max dates)

**Comment by qiarie** [comment]
### How to Replicate

1. Run the native-form sample app
2. Open **_BIRTH REGISTER_** form
3. Scroll to **_Child's DOB_** and tap to select a date
4. On the date picker dialog, select 30 or 31 for the day of the month selector
5. Try to scroll to 2 (February) on the month selector

### Solution

1. Reset the day of the month selector max value to 28 (29 if the selected year is a leap year) when the value selected in the month selector is 2 (February)

**Comment by ndegwamartin** [comment]
@qiarie to close this we need to : 

- [ ] Bump up the aritfact version
- [ ] Make the PR to both the `v1` and the `master` branch

**Comment by ndegwamartin** [comment]
Above relates to @qiarie to #577

**Comment by ndegwamartin** [comment]
Above comment relates to @qiarie to #577
